name: test
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Leonardo
          - name: Raphael
          - name: Donatello
          - name: Michelangelo
    outputs:
      names: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::${{ matrix.name }}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "outputs ${{needs.job1.outputs.names}}"
