name: test
on: push

env:
  APPS: |
    [
      { "name": "Leonardo" },
      { "name": "Raphael" },
      { "name": "Donatello" },
      { "name": "Michelangelo" },
    ]


jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.thing.outputs.test }}
    steps:
      - run: echo "${{ env.APPS }}"
      - id: thing
        run: echo "::set-output name=test::${{ env.APPS }}"
  job1:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix:
        apps: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - id: step1
        run: echo "${{ matrix.name }}"
  job2:
    runs-on: ubuntu-latest
    needs: [build-matrix, job1]
    steps:
      - run: echo "outputs ${{needs.build-matrix.outputs.matrix}}"
