name: test
on: push

env:
  APPS: |
    ${{ toJSON('[
      { "name": "Leonardo" },
      { "name": "Raphael" },
      { "name": "Donatello" },
      { "name": "Michelangelo" }
    ]')}}


jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix:
        include: ${{ steps.thing.outputs.test }}
    steps:
      - run: echo "${{ env.APPS }}"
      - id: thing
        run: echo "::set-output name=test::${{ env.APPS }}"
  check-output:
    runs-on: ubuntu-latest
    needs: build-matrix
    steps:
      - run: echo "${{needs.build-matrix.outputs.matrix}}"
      - run: echo "${{fromJSON(needs.build-matrix.outputs.matrix)[0].name}}"
  job1:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - id: step1
        run: echo "${{ matrix.name }}"
  job2:
    runs-on: ubuntu-latest
    needs: [build-matrix, job1]
    steps:
      - run: echo "outputs ${{needs.build-matrix.outputs.matrix}}"
